### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by bcicen**
Add setup script to make jenkins-cli an installable python package with commandline entrypoint.

Update readme with install steps.

### CODE REVIEW

**Comment by bcicen** [comment]
Resolves #7 and progresses #8 :)

**Comment by LD250** [comment]
I missed this PR somehow. I will merge it tomorrow.

**Comment by LD250** [comment]
Thank you for your PR, @bcicen, everything looks great.
But why do you think we need to rename console command to "jenkins-cli"? "jenkins" is shorter and I didn't found any conflicts.

**Comment by bcicen** [comment]
True, there doesn't seem to be any conflicts using just "jenkins"; I've pushed a commit reverting the change.

**Comment by LD250** [comment]
I will fix import issue on the master branch

**Pull request merged**
